CREATE ROLE debezium WITH LOGIN PASSWORD 'debezium';
ALTER ROLE debezium WITH REPLICATION;

GRANT CONNECT ON DATABASE appdb TO debezium;
GRANT USAGE ON SCHEMA public TO debezium;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO debezium;

ALTER TABLE roles REPLICA IDENTITY FULL; -- untuk update
